### PR TITLE
Timeline v2

### LINKED ISSUE #53: Support for Visa Card transactions
Trade Republic now has a Debit Visa Card available which spendings are taken out from the Cash account directly.
However, pytr (as of V0.1.9) does not include this entries in the generated account_transactions.csv file yet.
In addition to the actual spending additional round-up values might be added if the account holder configured it.
Therefore, when importing this file into tools like Portfolio Performance the reported Cash amount is off.

Please adapt the script to also produce these entries.

### PR DESCRIPTION
**Pull request by MartinScharrer**
Adds support for new Trade Republic API parts.
TR nows uses `timingTransaction` and `timelineActivityLog` instead of `timing` as well as `timingDetailV2` instead of `timingDetail`. 
As the new card transactions as well as saveback and round-up benefits are not included in the old API elements this change is required to include these. This pull-request fixes #53.

The naming of the output files and the format of the output JSON can be different from earlier versions.
The naming of the output files might be adapted further as they are now more information available in the  `timingDetailV2` data.

### CODE REVIEW

**Comment by yubiuser** [comment]
I tried your branch, but it fails with invalid date format

```
10:46:20 Write deposit entries
Traceback (most recent call last):
  File "main.py", line 236, in <module>
  File "main.py", line 212, in main
  File "asyncio/base_events.py", line 647, in run_until_complete
  File "dl.py", line 83, in dl_loop
  File "utils.py", line 447, in timelineDetail
  File "utils.py", line 220, in export_transactions
ValueError: Invalid isoformat string: '2024-05-15T18:45:28.540+0000'
[27842] Failed to execute script 'main' due to unhandled exception!
```

**Comment by Katzmann1983** [comment]
Alternatively here a full PR https://github.com/marzzzello/pytr/pull/66

**Comment by yubiuser** [comment]
Thanks. This fixed it for me.

I saw two types (ATM withdrawal and card order billing) which where not reflected in pytr currently, so I added them (set type to removal and added a note field)

https://github.com/yubiuser/pytr/commits/credit_card/

**Comment by daniel-w00** [comment]
Thanks. `pytr dldocs` works perfect now, i get all documents of Saveback, RoundUp and card transactions 

However i get errors regarding the timestamp while running `pytr dldocs --last_days`

> File "pytr\utils.py", line 329, in get_next_timeline_activity_log
>  
>    elif max_age_timestamp != 0 and timestamp < max_age_timestamp:
>     
> TypeError: '<' not supported between instances of 'str' and 'float'

**Comment by MartinScharrer** [comment]
@daniel-w00 Thanks for reporting this. Commit #6d7bc9f fix this.

**Comment by yubiuser** [comment]
@MartinScharrer your last commit introduced a new issue

```
08:18:24 Awaiting #1  timeline activity log
Traceback (most recent call last):
  File "main.py", line 236, in <module>
  File "main.py", line 212, in main
  File "asyncio/base_events.py", line 647, in run_until_complete
  File "dl.py", line 81, in dl_loop
  File "utils.py", line 350, in get_next_timeline_activity_log
ValueError: Invalid isoformat string: '2024-02-10T21:29:16.802+0000'
```

Which can be fixed by changing the line to 

```
timestamp = datetime.fromisoformat(response['items'][-1]['timestamp'][:19]).timestamp()
```

**Comment by daniel-w00** [comment]
the same error is in line 354 in utils.py which can be also be fixed with
` if max_age_timestamp != 0 and datetime.fromisoformat(event['timestamp'][:19]).timestamp() > max_age_timestamp:`
After that running `--last_days` works.
But I'm not sure if the output is intendend. `account_transactions.csv` lists all my transactions since opening the account nut just these from `last_days` like it was in the master branch.

Because of the ` except (ValueError, KeyError):` line 429 in utils.py the RoundUps also don't get filtered of course, which probably isn#t a big deal now.

**Pull request merged**
